/* ═══ 01 · Хүн, ураг төрөл, мэргэжил ═══ */
WB.dict.add({ id:"hun", label:"Хүн, нас, үүрэг", icon:"🧍", w:{
"хүн":"person","хүмүүс":"people","хүн төрөлхтөн":"humankind","хувь хүн":"individual","иргэн":"citizen",
"эмэгтэй":"woman","эмэгтэйчүүд":"women","эрэгтэй":"man","эрэгтэйчүүд":"men","бүсгүй":"young woman",
"хүүхэн":"woman","авгай":"married woman","эр":"male","эм":"female","хос":"couple","гэрлэгсэд":"married couple",
"охин":"girl","хүү":"boy","хүүхэд":"child","хүүхдүүд":"children","нярай":"newborn","нялх":"infant",
"балчир":"toddler","бага насны":"little","өсвөр насны":"teenage","өсвөр үе":"adolescence","залуу":"young",
"залуус":"young people","залуухан":"youthful","идэр":"in one's prime","насанд хүрэгч":"adult",
"дунд насны":"middle-aged","ахмад":"senior","хөгшин":"old","өвгөн":"old man","эмгэн":"old woman",
"настан":"elder","буурал":"grey-haired elder","өтөл":"aged","нас":"age","настай":"years old",
"нас бие":"physique","төрсөн":"born","төрсөн өдөр":"birthday","үе":"generation","үе тэнгийн":"of the same age",
"ноён":"lord","хатагтай":"lady","эзэн":"master","эзэгтэй":"mistress","гэрийн эзэн":"host",
"зочин":"guest","айлчлагч":"visitor","танил":"acquaintance","танихгүй хүн":"stranger","хөрш":"neighbour",
"нутгийн хүн":"local","гадаад хүн":"foreigner","жуулчин":"tourist","аялагч":"traveller","тэнүүлч":"wanderer",
"дүрвэгч":"refugee","цагаач":"migrant","оршин суугч":"resident","суурьшигч":"settler","нүүдэлчин":"nomad",
"баатар":"hero","эмэгтэй баатар":"heroine","гол дүр":"main character","туслах дүр":"supporting character",
"эсрэг дүр":"antagonist","өгүүлэгч":"narrator","гэрч":"witness","хохирогч":"victim","аврагч":"rescuer",
"удирдагч":"leader","манлайлагч":"frontrunner","дагалдагч":"follower","шавь":"disciple","сурагч":"pupil",
"багш":"teacher","мэргэн":"sage","мэргэжилтэн":"specialist","сонирхогч":"amateur","шинэхэн":"novice",
"найз":"friend","нөхөр":"companion","анд":"sworn friend","нөхөрлөл":"friendship","хамтрагч":"partner",
"хамт олон":"team","дайсан":"enemy","өрсөлдөгч":"rival","дайсагнагч":"adversary","хайрт":"beloved",
"амраг":"lover","сүйт бүсгүй":"bride","сүйт залуу":"groom","хань":"life partner","бэлэвсэн":"widowed",
"өнчин":"orphan","өргөмөл":"adopted child","ихэр":"twins","ганц хүүхэд":"only child",
"олон түмэн":"crowd","цуглаан":"gathering","бөөгнөрөл":"throng","бүлэг":"group","баг":"squad",
"хамтлаг":"band","эвсэл":"alliance","овог":"clan","аймаг":"tribe","угсаатан":"ethnic group",
"үндэстэн":"nation","ард түмэн":"the people","олон нийт":"the public","үзэгч":"viewer","үзэгчид":"audience",
"сонсогч":"listener","уншигч":"reader","дэмжигч":"supporter","шүтэн бишрэгч":"admirer",
"боол":"slave","зарц":"servant","шивэгчин":"maidservant","хөлсний хүн":"hired hand","ажилчин":"worker",
"ажилтан":"employee","дарга":"boss","захирал":"director","туслах":"assistant","нарийн бичиг":"secretary",
"гуйлгачин":"beggar","ядуу хүн":"pauper","баячууд":"the wealthy","язгууртан":"aristocrat","ноёрхогч":"ruler",
"хулгайч":"thief","дээрэмчин":"bandit","алуурчин":"assassin","луйварчин":"swindler","гэмт хэрэгтэн":"criminal",
"ялтан":"convict","хоригдол":"prisoner","олзлогдогч":"captive","эрэн сурвалжлагч":"investigator",
"хэн нэгэн":"someone","бүгд":"everyone","хэн ч":"anyone","бусад":"the others","өөр хүн":"another person"
}});

WB.dict.add({ id:"urag", label:"Ураг төрөл, гэр бүл", icon:"👪", w:{
"гэр бүл":"family","өрх":"household","ураг":"kin","садан":"relatives","төрөл":"relation",
"удам":"lineage","угсаа":"ancestry","удам угсаа":"pedigree","өвөг дээдэс":"ancestors","үр удам":"descendants",
"аав":"father","эцэг":"father","ээж":"mother","эх":"mother","эцэг эх":"parents","эцгийн":"paternal",
"эхийн":"maternal","ах":"older brother","эгч":"older sister","дүү":"younger sibling","охин дүү":"younger sister",
"эрэгтэй дүү":"younger brother","ах дүү":"siblings","ах дүүс":"brothers","эгч дүүс":"sisters",
"өвөө":"grandfather","эмээ":"grandmother","элэнц":"great-grandparent","хуланц":"great-great-grandparent",
"ач":"grandson","зээ":"granddaughter","ач зээ":"grandchildren","үр":"offspring","үр хүүхэд":"children",
"ганц хүү":"only son","отгон":"youngest child","ууган":"eldest child","дунд хүү":"middle son",
"авга ах":"paternal uncle","авга эгч":"paternal aunt","нагац ах":"maternal uncle","нагац эгч":"maternal aunt",
"үеэл":"cousin","бүл":"kinsman","хамаатан":"kinsfolk","эхнэр":"wife","нөхөр (гэр бүлийн)":"husband",
"бэр":"daughter-in-law","хүргэн":"son-in-law","бэргэн":"elder brother's wife","хадам":"in-law",
"хадам аав":"father-in-law","хадам ээж":"mother-in-law","ураг барилдах":"becoming in-laws",
"хүүхэд төрөх":"childbirth","өлгий":"cradle","нярайлах":"giving birth","хүүхэд өсгөх":"raising a child",
"өв":"inheritance","өв залгамжлагч":"heir","гэрлэлт":"marriage","хурим":"wedding","сүй":"betrothal",
"салалт":"divorce","гэр бүл цуцлах":"dissolving a marriage","гэрийн ажил":"housework","гэр орон":"home"
}});

WB.dict.add({ id:"mergejil", label:"Мэргэжил, ажил үйлс", icon:"🛠", w:{
"мэргэжил":"profession","ажил":"work","ажил мэргэжил":"occupation","албан тушаал":"post","хөдөлмөр":"labour",
"малчин":"herder","адуучин":"horse herder","хоньчин":"shepherd","тэмээчин":"camel herder","саальчин":"milkmaid",
"анчин":"hunter","загасчин":"fisherman","тариаланч":"farmer","цэцэрлэгч":"gardener","ойчин":"forester",
"уурхайчин":"miner","дархан":"blacksmith","мөнгөн дархан":"silversmith","алтан дархан":"goldsmith",
"мужаан":"carpenter","модчин":"woodcutter","чулуучин":"stonemason","ваарчин":"potter","нэхмэлчин":"weaver",
"оёдолчин":"tailor","гуталчин":"bootmaker","арьс ширчин":"tanner","эсгийчин":"felt maker","эмээлчин":"saddler",
"тогооч":"cook","талхчин":"baker","махчин":"butcher","зөгийчин":"beekeeper","айрагчин":"airag maker",
"эмч":"doctor","мэс засалч":"surgeon","сувилагч":"nurse","эм зүйч":"pharmacist","шүдний эмч":"dentist",
"мал эмнэлэгч":"veterinarian","эмнэлгийн ажилтан":"medic","сэтгэл зүйч":"psychologist",
"багш":"teacher","профессор":"professor","эрдэмтэн":"scholar","судлаач":"researcher","түүхч":"historian",
"археологич":"archaeologist","газарзүйч":"geographer","одон орон судлаач":"astronomer","биологич":"biologist",
"физикч":"physicist","химич":"chemist","математикч":"mathematician","хэл шинжлэгч":"linguist",
"орчуулагч":"translator","хэлмэрч":"interpreter","номын санч":"librarian","архивч":"archivist",
"зохиолч":"writer","яруу найрагч":"poet","сэтгүүлч":"journalist","сурвалжлагч":"reporter","редактор":"editor",
"хэвлэн нийтлэгч":"publisher","шүүмжлэгч":"critic","блогч":"blogger",
"зураач":"painter","уран барималч":"sculptor","график дизайнер":"graphic designer","дизайнер":"designer",
"уран бүтээлч":"artist","гэрэл зурагчин":"photographer","чимэглэгч":"decorator","гоо сайхны мэргэжилтэн":"beautician",
"дуучин":"singer","хөгжимчин":"musician","хөгжмийн зохиолч":"composer","удирдаач":"conductor","бүжигчин":"dancer",
"бүжиг дэглээч":"choreographer","жүжигчин":"actor","найруулагч":"director","продюсер":"producer",
"зураглаач":"cinematographer","монтажчин":"film editor","гримчин":"make-up artist","хувцаслагч":"costumer",
"каскадёр":"stunt performer","дуу оруулагч":"voice actor","тайз засагч":"set designer","гэрэлтүүлэгч":"gaffer",
"инженер":"engineer","программист":"programmer","архитектор":"architect","барилгачин":"builder",
"өрлөгчин":"bricklayer","цахилгаанчин":"electrician","сантехникч":"plumber","гагнуурчин":"welder",
"механикч":"mechanic","засварчин":"repairman","жолооч":"driver","нисгэгч":"pilot","далайчин":"sailor",
"галт тэрэгний жолооч":"train driver","хүргэлтийн ажилтан":"courier","ачигч":"loader",
"худалдагч":"shopkeeper","худалдаачин":"merchant","наймаачин":"trader","нярав":"storekeeper",
"нягтлан бодогч":"accountant","эдийн засагч":"economist","банкир":"banker","зуучлагч":"broker",
"менежер":"manager","маркетингч":"marketer","үйлчлэгч":"attendant","зөөгч":"waiter","үсчин":"barber",
"хуульч":"lawyer","өмгөөлөгч":"defence counsel","прокурор":"prosecutor","шүүгч":"judge","нотариатч":"notary",
"цагдаа":"police officer","мөрдөгч":"detective","харуул":"guard","хамгаалагч":"bodyguard","жижүүр":"watchman",
"гал сөнөөгч":"firefighter","аврагч":"rescuer","хилчин":"border guard","цэрэг":"soldier","офицер":"officer",
"жанжин":"general","дайчин":"warrior","харваач":"archer","морин цэрэг":"cavalryman","тагнуулч":"spy",
"элч":"envoy","дипломат":"diplomat","түшмэл":"official","сайд":"minister","захирагч":"governor",
"лам":"monk","хамба":"abbot","гэлэн":"fully ordained monk","банди":"novice monk","бөө":"shaman",
"зайран":"male shaman","удган":"female shaman","зурхайч":"astrologer","төлгөч":"diviner","эмчлэгч":"healer",
"тамирчин":"athlete","дасгалжуулагч":"coach","бөх":"wrestler","уяач":"horse trainer","унаач":"jockey",
"илбэчин":"magician","циркчин":"circus performer","хөтлөгч":"host","загвар өмсөгч":"model"
}});
