/* ═══ 02 · Бие, царай, харагдац, эрүүл мэнд ═══ */
WB.dict.add({ id:"bie", label:"Бие, эрхтэн", icon:"🫀", w:{
"бие":"body","биеийн":"bodily","махбод":"flesh","дүр":"figure","бие бялдар":"physique","биеийн байдал":"posture",
"толгой":"head","гавал":"skull","тархи":"brain","дух":"forehead","духан":"brow","зулай":"crown of the head",
"нүүр":"face","царай":"face","царайлаг":"good-looking","төрх":"appearance","дүр төрх":"look",
"нүд":"eyes","нүдний хүүхэн хараа":"pupil","солонго бүрхэвч":"iris","зовхи":"eyelid","сормуус":"eyelashes",
"хөмсөг":"eyebrows","харц":"gaze","хараа":"vision","нулимс":"tears","нүдний ирмэг":"corner of the eye",
"хамар":"nose","хамрын нүх":"nostril","хамрын гүүр":"bridge of the nose","ам":"mouth","уруул":"lips",
"дээд уруул":"upper lip","доод уруул":"lower lip","шүд":"teeth","соёо":"fang","хэл":"tongue","тагнай":"palate",
"эрүү":"chin","эрүүний яс":"jaw","хацар":"cheeks","хацрын яс":"cheekbones","чих":"ears","чихний дэлбээ":"earlobe",
"хүзүү":"neck","хоолой":"throat","гуя":"thigh","мөр":"shoulders","мөрний ир":"shoulder blade","гар":"hands",
"суга":"armpit","тохой":"elbow","бугуй":"wrist","алга":"palm","хуруу":"fingers","эрхий хуруу":"thumb",
"долоовор хуруу":"index finger","дунд хуруу":"middle finger","чигчий":"little finger","хумс":"nails",
"цээж":"chest","хавирга":"ribs","өвөр":"bosom","нуруу":"back","нурууны яс":"spine","бэлхүүс":"waist",
"хэвлий":"abdomen","гэдэс":"belly","хонго":"hip","өгзөг":"buttocks","хөл":"legs","өвдөг":"knee",
"тахим":"back of the knee","шилбэ":"shin","шагай":"ankle","өсгий":"heel","ул":"sole","хөлийн хуруу":"toes",
"арьс":"skin","үс":"hair","үсний ширхэг":"strand of hair","үндэс (үсний)":"hair root","сахал":"beard",
"тахир сахал":"moustache","хөмсөгний үс":"brow hair","яс":"bone","үе мөч":"joint","булчин":"muscle",
"шөрмөс":"tendon","судас":"vein","цус":"blood","зүрх":"heart","уушиг":"lungs","элэг":"liver","бөөр":"kidney",
"ходоод":"stomach","гэдэс дотор":"intestines","дэлүү":"spleen","мэдрэл":"nerve","амьсгал":"breath",
"зүрхний цохилт":"heartbeat","судасны цохилт":"pulse","хөлс":"sweat","шүлс":"saliva","нойр":"sleep",
"хоолой (дуу)":"voice box","дуу хоолой":"voice","инээмсэглэл":"smile","инээд":"laughter","ёолол":"groan"
}});

WB.dict.add({ id:"haragdats", label:"Харагдац, царайны шинж", icon:"🪞", w:{
"үзэсгэлэнтэй":"beautiful","гоо үзэсгэлэн":"beauty","гоё":"lovely","гоолиг":"graceful","дэгжин":"elegant",
"эрхэмсэг":"dignified","сүрлэг":"majestic","эгэлгүй":"striking","дур булаам":"charming","татахуйц":"attractive",
"царайлаг эр":"handsome man","аятайхан":"pleasant-looking","энгийн төрхтэй":"plain-looking","муухай":"ugly",
"аймшигтай төрхтэй":"frightening in appearance","хачирхалтай":"odd-looking","эвгүй":"awkward",
"туранхай":"slender","нарийхан":"slim","гонзгой":"elongated","дүүрэн биетэй":"full-bodied","тарган":"heavy-set",
"булчинлаг":"muscular","бөх бөгс":"sturdy","хүчирхэг":"powerful","эмзэг":"frail","сул дорой":"weak",
"өндөр":"tall","намхан":"short in stature","дунд зэргийн":"of medium build","эгц":"upright","бөгтөр":"hunched",
"мөр нь унжсан":"slouched","цээжээ тэлсэн":"chest thrust out","хөнгөн хөдөлгөөнтэй":"light-footed",
"хатуу царайтай":"stern-faced","зөөлөн царайтай":"soft-featured","дугуй царайтай":"round-faced",
"өндөр хацрын ястай":"high-cheekboned","хурц шинжтэй":"sharp-featured","үрчлээтэй":"wrinkled",
"үрчлээ":"wrinkles","сорви":"scar","мэнгэ":"mole","сэвх":"freckles","батга":"acne","шивээс":"tattoo",
"цайвар арьстай":"pale-skinned","бараан арьстай":"dark-skinned","бор арьстай":"tanned","улайсан":"flushed",
"цонхигор":"pallid","гэрэлтсэн арьс":"glowing skin","хуурай арьс":"dry skin","гөлгөр арьс":"smooth skin",
"урт үс":"long hair","богино үс":"short hair","мөр хүрэм үс":"shoulder-length hair","сүлжсэн үс":"braided hair",
"хос гэзэг":"twin braids","боосон үс":"tied-up hair","задгай үс":"loose flowing hair","самнасан үс":"combed hair",
"үймсэн үс":"tousled hair","буржгар үс":"curly hair","долгиолсон үс":"wavy hair","шулуун үс":"straight hair",
"өтгөн үс":"thick hair","сийрэг үс":"thinning hair","хар үс":"black hair","бор үс":"brown hair",
"шаргал үс":"blonde hair","улаан үс":"red hair","буурал үс":"greying hair","цагаан үс":"white hair",
"мөнгөлөг үс":"silvery hair","хусуулсан толгой":"shaved head","халзан":"bald","гэзэг":"queue braid",
"хар нүд":"dark eyes","хүрэн нүд":"brown eyes","хөх нүд":"blue eyes","саарал нүд":"grey eyes",
"ногоон нүд":"green eyes","нарийн нүд":"narrow eyes","том нүд":"large eyes","гүн нүд":"deep-set eyes",
"хурц харц":"piercing gaze","дулаан харц":"warm gaze","хүйтэн харц":"cold stare","ядарсан харц":"weary look",
"тодорхойгүй харц":"vacant stare","инээмсэглэсэн":"smiling","хөмсөг зангидсан":"frowning",
"уруул зуусан":"biting the lip","ам ангайсан":"open-mouthed","нүдээ анисан":"eyes closed",
"нүд гялалзсан":"eyes shining","нулимстай нүд":"tearful eyes","улаан хацартай":"rosy-cheeked"
}});

WB.dict.add({ id:"eruul", label:"Эрүүл мэнд, өвчин", icon:"🩺", w:{
"эрүүл":"healthy","эрүүл мэнд":"health","өвчин":"illness","өвчтэй":"ill","сул дорой байдал":"weakness",
"халуурах":"having a fever","халуун (өвчний)":"fever","ханиад":"cold","ханиалгах":"coughing","найтаах":"sneezing",
"толгой өвдөх":"headache","толгой эргэх":"dizziness","дотор муухайрах":"nausea","бөөлжих":"vomiting",
"өвдөлт":"pain","өвдөх":"aching","хатгах (өвдөлт)":"stabbing pain","загатнах":"itching","хавдах":"swelling",
"шарх":"wound","шархадсан":"wounded","цус алдах":"bleeding","хугарал":"fracture","мултрал":"dislocation",
"түлэгдэл":"burn","хөлдөлт":"frostbite","хөх толбо":"bruise","сорви үлдэх":"scarring","эдгэрэх":"healing",
"эдгэрэлт":"recovery","сэргэх":"reviving","эм":"medicine","эмчилгээ":"treatment","мэс засал":"surgery",
"тариа (эмийн)":"injection","боолт":"bandage","эмнэлэг":"hospital","түргэн тусламж":"ambulance",
"өвчтөн":"patient","онош":"diagnosis","халдвар":"infection","тахал":"epidemic","хорио цээр":"quarantine",
"хоол тэжээл":"nutrition","дасгал":"exercise","амралт":"rest","нойргүйдэл":"insomnia","ядрах":"tiring",
"ядарсан":"exhausted","сульдах":"languishing","хүч орох":"regaining strength","тэнхээ":"stamina",
"хөгжлийн бэрхшээлтэй":"disabled","сохор":"blind","дүлий":"deaf","хэлгүй":"mute","доголон":"lame",
"таяг":"crutch","тэргэнцэр":"wheelchair","нүдний шил":"eyeglasses","сонсох аппарат":"hearing aid",
"үхэл":"death","үхэх":"dying","амьсгал хураах":"passing away","үхсэн":"dead","цогцос":"corpse",
"оршуулга":"burial","гашуудал":"mourning","амьдрал":"life","амьд":"alive","амьсгаа":"breathing",
"төрөлт":"birth","өсөлт":"growth","хөгшрөлт":"ageing","сэтгэцийн":"mental","бие махбодын":"physical"
}});
