/* ═══ 05 · Байгаль, газарзүй, тэнгэр, ургамал ═══ */
WB.dict.add({ id:"gazar", label:"Газар зүй, ландшафт", icon:"🏔", w:{
"байгаль":"nature","орчин":"environment","газар":"land","газар нутаг":"terrain","талбай":"field",
"тал":"steppe","хээр":"open steppe","хээр тал":"steppe plain","өргөн тал":"broad plain","тэгш тал":"flatland",
"нуга":"meadow","бэлчээр":"pasture","цайдам":"salt flat","хужир":"saline soil","говь":"Gobi desert",
"цөл":"desert","элс":"sand","элсэн манхан":"sand dune","манхан":"dune","хайрга":"gravel",
"уул":"mountain","уулс":"mountains","уулын нуруу":"mountain range","оргил":"summit","орой (уулын)":"peak",
"даваа":"mountain pass","хяр":"ridge","хажуу":"slope","бэл":"foot of a mountain","ам (уулын)":"mountain valley mouth",
"хөндий":"valley","хавцал":"gorge","жалга":"ravine","гуу":"gully","хад":"cliff","хадан хясаа":"rocky crag",
"хясаа":"outcrop","чулуу":"stone","хад чулуу":"boulders","овоо":"ovoo (sacred cairn)","дов":"mound",
"толгод":"hills","толгой (уулын)":"hillock","тэгш өндөрлөг":"plateau","хотгор":"hollow","гүдгэр":"rise",
"агуй":"cave","нүх":"pit","цоорхой":"crevice","ан цав":"crack in the ground","галт уул":"volcano",
"галт уулын ам":"crater","хайлмаг чулуу":"lava","газар хөдлөлт":"earthquake","нуралт":"landslide",
"ой":"forest","ойт хээр":"forest steppe","тайга":"taiga","төгөл":"grove","шугуй":"thicket","модлог":"woodland",
"гол":"river","голын эрэг":"riverbank","горхи":"stream","булаг":"spring","рашаан":"mineral spring",
"нуур":"lake","цөөрөм":"pond","шалбааг":"puddle","намаг":"marsh","намгархаг":"boggy","татам":"floodplain",
"далай":"sea","тэнгис":"ocean","арал":"island","хойг":"peninsula","хошуу (газар)":"headland","эрэг":"shore",
"элсэн эрэг":"sandy beach","хүрхрээ":"waterfall","урсгал":"current","давалгаа":"wave","цалгиа":"ripple",
"мөс":"ice","мөсөн гол":"glacier","мөстөл":"ice sheet","цас":"snow","цасан бүрхүүл":"snow cover",
"шороо":"soil","хөрс":"earth","тоос":"dust","шавар":"mud","шавхай":"slush","хуурай газар":"dry land",
"зам":"road","шороон зам":"dirt track","мөр (замын)":"track","жим":"trail","гүүр":"bridge",
"уулзвар":"crossroads","хил":"border","хязгаар":"frontier","алслагдсан газар":"remote place",
"эзгүй газар":"deserted place","онгон байгаль":"untouched wilderness","бэлчээрийн газар":"grazing land",
"тариалангийн талбай":"cropland","ургац":"harvest","газрын гадарга":"ground surface","өндөрлөг":"highland",
"нам дор газар":"lowland","хотос":"basin","салхины ам":"wind-swept gap","эх (голын)":"river source",
"адаг":"river mouth","аралжин":"river island","гүехэн газар":"shallows","гүн ус":"deep water"
}});

WB.dict.add({ id:"tenger", label:"Тэнгэр, цаг агаар, улирал", icon:"🌤", w:{
"тэнгэр":"sky","огторгуй":"firmament","орчлон":"universe","сансар":"space","нар":"sun","нарны туяа":"sunbeam",
"сар":"moon","хагас сар":"half moon","бүтэн сар":"full moon","хавирган сар":"crescent moon","од":"star",
"одод":"stars","одон":"celestial body","сүүн зам":"Milky Way","гараг":"planet","сүүлт од":"comet",
"солир":"meteor","нар хиртэлт":"solar eclipse","хойд туйлын туяа":"aurora","үүл":"cloud","үүлс":"clouds",
"цагаан үүл":"white cloud","хар үүл":"dark cloud","бөөн үүл":"cumulus cloud","нимгэн үүл":"wispy cloud",
"үүлгүй":"cloudless","цэлмэг":"clear sky","бүрхэг":"overcast","солонго":"rainbow","манан":"fog",
"будан":"mist","униар":"haze","утаа":"smoke","тортог":"soot","салхи":"wind","салхитай":"windy",
"сэвшээ салхи":"breeze","хүчтэй салхи":"strong wind","хуй салхи":"whirlwind","шуурга":"storm",
"цасан шуурга":"blizzard","шороон шуурга":"dust storm","аадар":"downpour","бороо":"rain",
"шиврээ бороо":"drizzle","борооны дусал":"raindrop","мөндөр":"hail","цас орох":"snowfall",
"цасан ширхэг":"snowflake","хяруу":"frost","шүүдэр":"dew","мөстөл (замын)":"black ice","гэсэлт":"thaw",
"аянга":"lightning","тэнгэрийн дуу":"thunder","цахилгаан (аянгын)":"lightning flash","бүрхэг өдөр":"grey day",
"нартай өдөр":"sunny day","халуун":"hot","халуун оргих":"scorching","дулаан":"warm","сэрүүн":"cool",
"хүйтэн":"cold","хүйтэн жавар":"bitter cold","жавар":"frosty air","хяруутай":"frosty","чийглэг":"humid",
"хуурай (агаар)":"dry air","агаар":"air","цэвэр агаар":"fresh air","уур":"vapour","чийг":"moisture",
"улирал":"season","хавар":"spring","зун":"summer","намар":"autumn","өвөл":"winter","хаврын":"vernal",
"зуны":"summery","намрын":"autumnal","өвлийн":"wintry","цаг агаар":"weather","уур амьсгал":"climate",
"нар мандах":"sunrise","үүр цайх":"daybreak","үүрийн гэгээ":"first light","өглөөний нар":"morning sun",
"үд дунд":"midday","нар шингэх":"sundown","нар жаргах":"sunset","бүрий":"dusk","бүрэнхий":"twilight",
"харанхуй болох":"nightfall","шөнө дунд":"midnight","сарны гэрэл":"moonlight","одтой шөнө":"starry night",
"алтан цаг":"golden hour","хөх цаг":"blue hour","эрэг дэх манан":"mist over the shore","салхины чимээ":"sound of wind"
}});

WB.dict.add({ id:"urgamal", label:"Ургамал, мод, цэцэг", icon:"🌿", w:{
"ургамал":"plant","ургамлан бүрхэвч":"vegetation","мод":"tree","модод":"trees","залуу мод":"sapling",
"хуучин мод":"old tree","хатсан мод":"dead tree","гуалиг мод":"slender tree","их бие":"tree trunk",
"мөчир":"branch","салаа мөчир":"forked branch","навч":"leaf","навчис":"foliage","шилмүүс":"needles",
"үндэс":"root","холтос (модны)":"tree bark","сүүдэр (модны)":"tree shade","навч унах":"leaf fall",
"нахиа":"bud","цэцэг":"flower","цэцэглэлт":"blossoming","дэлбээ":"petal","тоос (цэцгийн)":"pollen",
"үр":"seed","жимсний мод":"fruit tree","самрын мод":"nut tree","хус":"birch","нарс":"pine","гацуур":"spruce",
"шинэс":"larch","улиас":"poplar","бургас":"willow","хайлаас":"elm","хар мод":"blackwood","заг":"saxaul",
"хайрган бут":"scrub bush","бут":"bush","сөөг":"shrub","өвс":"grass","өндөр өвс":"tall grass",
"шар өвс":"yellow grass","ногоон өвс":"green grass","хатсан өвс":"withered grass","хагд":"dead grass",
"хялгана":"feather grass","дэрс":"tall steppe grass","хиаг":"couch grass","улалж":"sedge","зэгс":"reeds",
"шагшуурга":"rushes","хөвд":"moss","хагны":"lichen","мөөг":"mushroom","ойн мөөг":"forest mushroom",
"цагаан цэцэг":"white flower","улаан цэцэг":"red flower","хээрийн цэцэг":"steppe flower","алтан гагнуур":"golden root",
"цахилдаг":"iris flower","алтанзул":"tulip","улаанбудаа":"red millet","гүзээлзгэнийн бут":"strawberry bush",
"ноорхой бут":"tangled bush","өргөс":"thorn","өргөстэй":"thorny","хатгуур ургамал":"prickly plant",
"эмийн ургамал":"medicinal herb","ханд":"herbal extract","үнэрт ургамал":"aromatic herb","шарилж":"wormwood",
"таана":"wild onion","хумул":"wild chive","мангир":"wild garlic","хөмүүл":"wild leek","хулс":"bamboo",
"ой мод":"woods","модлог ургамал":"woody plant","ногоорох":"turning green","цэцэглэх":"blooming",
"хатах":"withering","навчилах":"leafing out","үрждэг":"propagating","ургац хураах":"harvesting",
"тариа":"crop","улаан буудай":"wheat","арвай":"barley","овъёос":"oats","эрдэнэ шиш":"maize","хивэг":"chaff"
}});
