/* ═══ 09 · Сэтгэл хөдлөл, зан чанар, харилцаа ═══ */
WB.dict.add({ id:"setgel", label:"Сэтгэл хөдлөл", icon:"💗", w:{
"сэтгэл":"heart","сэтгэл хөдлөл":"emotion","мэдрэмж":"feeling","сэтгэлийн байдал":"state of mind",
"уур амьсгал (сэтгэлийн)":"mood","баяр":"joy","баяртай":"joyful","баясгалан":"delight","хөгжилтэй":"cheerful",
"аз жаргал":"happiness","жаргалтай":"happy","сэтгэл хангалуун":"content","тайвширсан":"relieved",
"урам":"enthusiasm","урамтай":"eager","догдлол":"excitement","догдолсон":"thrilled","хөөрсөн":"elated",
"гуниг":"sorrow","гунигтай":"sorrowful","уйтгар":"melancholy","уйтгартай":"melancholic","гашуудал":"grief",
"гашуудсан":"grieving","харуусал":"regret","харамсал":"remorse","харамссан":"rueful","эмгэнэл":"tragedy",
"уй":"woe","цөхрөл":"despair","цөхөрсөн":"despairing","найдвар":"hope","найдвартай":"hopeful",
"найдвар тасрах":"losing hope","хүсэл":"desire","хүсэн хүлээх":"yearning","мөрөөдөл":"dream",
"мөрөөдөмтгий":"dreamy","санагалзал":"longing","дурсал":"nostalgia","гэрийн санаа":"homesickness",
"уур":"anger","уурласан":"angry","хилэн":"fury","хилэгнэсэн":"enraged","бухимдал":"frustration",
"бухимдсан":"frustrated","дургүйцэл":"displeasure","жигшил":"disgust","үзэн ядалт":"hatred",
"өшөө":"vengeance","өс хонзон":"grudge","атаархал":"jealousy","атаархсан":"envious","шунал":"greed",
"айдас":"fear","айсан":"frightened","аймшиг":"terror","сүрдсэн":"awestruck","түгшүүр":"anxiety",
"түгшсэн":"anxious","сандрал":"panic","сандарсан":"panicked","эргэлзээ":"doubt","эргэлзсэн":"hesitant",
"тодорхойгүй байдал":"uncertainty","гайхал":"wonder","гайхсан":"astonished","цочирдсон":"stunned",
"сониуч":"curious","сонирхол":"interest","уйтгар (уйдах)":"boredom","уйдсан":"bored","залхуурал":"listlessness",
"ичгүүр":"shame","ичсэн":"embarrassed","гутрал":"dejection","гутарсан":"downcast","бахархал":"pride",
"бахархсан":"proud","өөртөө итгэх":"self-assurance","итгэл":"trust","итгэсэн":"trusting","үл итгэх":"distrust",
"хайр":"love","хайртай":"in love","энэрэл":"compassion","өрөвдөл":"pity","өршөөл":"mercy","уучлал":"forgiveness",
"талархал":"gratitude","талархсан":"grateful","хүндэтгэл":"respect","биширсэн":"admiring","бишрэл":"adoration",
"эмзэглэл":"tenderness","халуун сэтгэл":"warmth of heart","ганцаардал":"loneliness","ганцаардсан":"lonely",
"хоосон сэтгэл":"emptiness","тайван":"calm","амар тайван":"at peace","тайвшрал":"solace","чимээгүй баяр":"quiet joy",
"хүлээлт":"anticipation","тэвчээр":"patience","тэвчээргүй":"impatient","эвгүйрхсэн":"ill at ease",
"сэтгэл догдлол":"heart-flutter","нулимс унагах":"shedding tears","сэтгэл хөдөлсөн":"moved"
}});

WB.dict.add({ id:"zanchanar", label:"Зан чанар, төлөв", icon:"🧠", w:{
"зан":"temperament","зан чанар":"character","араншин":"disposition","дадал":"habit","зуршил":"custom",
"хүсэл эрмэлзэл":"aspiration","зорилго":"purpose","хүсэл зориг":"willpower","шийдэмгий":"decisive",
"шийдвэргүй":"indecisive","зоригтой":"brave","зориг":"courage","эрэлхэг":"valiant","зүрхтэй":"bold",
"аймхай":"timid","хулчгар":"cowardly","ичимхий":"shy","даруу":"modest","өөртөө итгэлтэй":"confident",
"их зантай":"arrogant","бардам":"haughty","дээрэнгүй":"condescending","дуулгавартай":"obedient",
"зөрүүд":"stubborn","хатуу зөрүүд":"headstrong","өөрийн үзэлтэй":"opinionated","уян хатан":"adaptable",
"тэвчээртэй":"patient","хурц ааштай":"hot-tempered","тайван ааштай":"even-tempered","ууртай зантай":"irascible",
"эелдэг":"polite","найрсаг":"friendly","нээлттэй":"open","дотно":"intimate","хөндий":"aloof",
"хүйтэн зантай":"cold-mannered","бүдүүлэг":"rude","хэрцгий":"cruel","ширүүн":"harsh","хатуу":"severe",
"зөөлөн":"gentle","эелдэг зөөлөн":"mild-mannered","өгөөмөр":"generous","харамч":"stingy","шударга":"honest",
"үнэнч":"loyal","итгэлтэй хүн":"reliable person","худалч":"deceitful","хууран мэхлэгч":"cheat",
"зальтай":"cunning","мэхэлсэн":"deceived","илэн далангүй":"frank","нууцлаг":"mysterious","дуугүй":"taciturn",
"ярианч":"talkative","хөгжилтэй зантай":"jovial","хошин":"humorous","инээдтэй":"amusing","ноцтой":"serious",
"хатуужилтай":"resilient","хүчтэй сэтгэлтэй":"strong-willed","эмзэг сэтгэлтэй":"sensitive","мэдрэмтгий":"perceptive",
"ухаантай":"clever","мэргэн ухаантай":"wise","гярхай":"sharp-eyed","авьяастай":"talented","чадварлаг":"skilled",
"тэнэг":"foolish","мунхаг":"ignorant","гэнэн":"naive","хачин":"eccentric","солиотой":"deranged",
"хичээнгүй":"diligent","хөдөлмөрч":"industrious","залхуу":"lazy","хайхрамжгүй":"indifferent","хариуцлагатай":"responsible",
"хариуцлагагүй":"irresponsible","болгоомжтой":"cautious","болгоомжгүй":"reckless","тэсвэртэй":"enduring",
"тэвчээр алдсан":"having lost patience","эрч хүчтэй":"energetic","идэвхтэй":"active","идэвхгүй":"passive",
"нухацтай":"thoughtful","бодлогошронгуй":"pensive","мартамхай":"forgetful","анхаарамжтай":"attentive",
"тэнүүчилсэн":"restless","дэггүй":"mischievous","эрхлүүлсэн":"spoilt","хүлээцтэй":"tolerant","цээрлэсэн":"restrained"
}});

WB.dict.add({ id:"hariltsaa", label:"Харилцаа, яриа", icon:"💬", w:{
"харилцаа":"relationship","яриа":"conversation","ярилцлага":"interview","хэлэлцүүлэг":"discussion",
"маргаан":"argument","хэрүүл":"quarrel","зөвшилцөл":"agreement","тохиролцоо":"deal","гэрээ (хэлцэл)":"contract",
"амлалт":"promise","тангараг":"oath","үг":"word","өгүүлбэр":"sentence","хэллэг":"phrase","яриа хөөрөө":"chatter",
"шивнээ":"whisper","хашгираан":"shout","дуудлага":"call","хариулт":"answer","асуулт":"question",
"хүсэлт":"request","тушаал":"command","зөвлөгөө":"advice","сануулга":"reminder","анхааруулга":"warning",
"мэдээ":"news","мэдээлэл":"information","цуурхал":"rumour","хов":"gossip","нууц":"secret","илчлэлт":"revelation",
"үнэн":"truth","худал":"lie","хуурамч":"false","баримт":"fact","нотолгоо":"proof","гэрчлэл":"testimony",
"тайлбар":"explanation","учир":"reason","шалтгаан":"cause","үр дүн":"result","дүгнэлт":"conclusion",
"санал":"suggestion","санаа":"idea","бодол":"thought","үзэл":"view","байр суурь":"stance","сэтгэгдэл":"impression",
"шүүмжлэл":"criticism","магтаал":"praise","талархлын үг":"words of thanks","уучлалт":"apology",
"мэндчилгээ":"greeting","золголт":"formal greeting","баяр хүргэх":"congratulating","ерөөл":"blessing",
"хараал":"curse","доромжлол":"insult","заналхийлэл":"threat","гуйлт":"plea","залбирал":"prayer",
"дуудлага (утсаар)":"phone call","захидал":"letter","мессеж":"message","илгээмж":"parcel","хариу бичих":"replying",
"уулзалт":"meeting","салах ёс":"farewell","угтах":"welcoming","үдэх":"seeing off","танилцах":"getting acquainted",
"итгэл алдах":"losing trust","эвлэрэх":"reconciling","эв нэгдэл":"unity","дэмжлэг":"support","хамтын ажиллагаа":"cooperation",
"өрсөлдөөн":"competition","зөрчил":"conflict","эв таарахгүй":"discord","хүлээн зөвшөөрөх":"acknowledging",
"татгалзал":"refusal","зөвшөөрөл":"permission","хориг":"prohibition","шаардлага":"demand","гомдол":"complaint",
"гомдсон":"hurt","өршөөл гуйх":"begging pardon","ойлголцол":"mutual understanding","үл ойлголцол":"misunderstanding"
}});
