/* ═══ 10 · Үйл үг ═══ */
WB.dict.add({ id:"verb-move", label:"Үйл үг · хөдөлгөөн", icon:"🏃", w:{
"байх":"being","болох":"becoming","хийх":"doing","үйлдэх":"acting","эхлэх":"beginning","дуусах":"ending",
"үргэлжлэх":"continuing","зогсоох":"stopping","явах":"going","ирэх":"coming","хүрэх":"arriving",
"буцах":"returning","орох":"entering","гарах":"going out","өнгөрөх":"passing by","дайрах (замд)":"passing through",
"алхах":"walking","алхаж явах":"strolling","гүйх":"running","хурдлан гүйх":"sprinting","чирэгдэн явах":"trudging",
"хөл нүцгэн алхах":"walking barefoot","гишгэх":"stepping","гишгэлэх":"treading","дэвших":"advancing",
"ухрах":"backing away","эргэх":"turning","эргэлдэх":"spinning","тойрох":"circling","дайран өнгөрөх":"sweeping past",
"зогсох":"standing","суух":"sitting","хэвтэх":"lying down","бөхийх":"bending down","сөгдөх":"kneeling",
"тонгойх":"stooping","тэнийх":"straightening up","босох":"rising","үсрэх":"leaping","харайх":"jumping",
"унах":"falling","бүдрэх":"stumbling","гулсах":"slipping","эргэлдэн унах":"tumbling","нурах":"collapsing",
"нисэх (агаарт)":"flying","хөвөх":"drifting","сэлэх":"swimming","живэх":"sinking","хөвж гарах":"surfacing",
"мацах":"climbing","өгсөх":"ascending","буух":"descending","уруудах":"going downhill","гүйлгэх":"letting run",
"мордох (морь)":"mounting","давхих (морьтой)":"riding at a gallop","жолоодох":"driving","хөтлөх":"leading by hand",
"дагах":"following","хөөх":"chasing","хөөцөлдөх":"pursuing","зугтах":"fleeing","оргох":"escaping",
"нуугдах":"hiding","бүгэх":"lying in wait","мөлхөх":"crawling","чичрэх":"trembling","салганах":"shaking",
"найгах":"swaying","ганхах":"rocking","дүүжлэгдэх":"dangling","эргэлдэн хийсэх":"whirling",
"хийсэх":"being blown","савсах":"fluttering","дэрвэх":"flapping in the wind","намирах":"waving",
"урсах":"flowing","дуслах":"dripping","цутгах":"pouring","оргилох":"gushing","үсрэх (ус)":"splashing",
"бударах":"swirling","тархах":"spreading","цацрах":"scattering","бөөгнөрөх":"clustering","цугларах":"gathering",
"тарах":"dispersing","ойртох":"approaching","холдох":"receding","салах":"parting","нийлэх":"joining",
"уулзах":"meeting","гүйцэх":"catching up","түрүүлэх":"getting ahead","хоцрох":"falling behind",
"хөдлөх":"moving off","хөдөлгөх":"setting in motion","чиглэх":"heading toward","эргэж харах":"looking back",
"тэмтрэх":"groping","хайх":"searching","олох":"finding","алдах":"losing","орхих":"leaving behind",
"хүлээх":"waiting","амрах":"resting","сунах":"stretching","хэлбийх":"leaning","налах":"leaning against"
}});

WB.dict.add({ id:"verb-hand", label:"Үйл үг · гар үйлдэл", icon:"✋", w:{
"барих":"holding","атгах":"gripping","тэвэрч барих":"clutching","суллах":"releasing","тавих":"placing",
"өгөх":"giving","авах":"taking","сунгах (гараа)":"reaching out","хүрэх (гараар)":"touching","илбэх":"stroking",
"таталцах":"tugging","татах":"pulling","түлхэх":"pushing","өргөх":"lifting","буулгах":"setting down",
"шидэх":"throwing","шидэн унагах":"hurling","барьж авах":"catching","алдах (гараас)":"dropping",
"нээх":"opening","хаах":"closing","түгжих":"locking","тайлах":"untying","уях":"tying","боох":"wrapping",
"задлах":"unwrapping","эвхэх":"folding","дэлгэх":"unfolding","хийх (сав руу)":"putting in","цутгах (сав руу)":"pouring in",
"хутгах":"stirring","хольж хутгах":"mixing","зүсэх":"slicing","хэрчих":"chopping","огтлох":"cutting off",
"хайчлах":"trimming","хусах":"scraping","цоолох":"piercing","өрөмдөх":"drilling","хадах":"nailing",
"наах":"sticking on","салгах":"detaching","эвдэх":"breaking","хугалах":"snapping","хагалах":"splitting",
"бутлах":"crushing","нухах":"kneading","шахах":"pressing","мушгих":"twisting","сунгах":"stretching out",
"цэвэрлэх":"cleaning","угаах":"washing","арчих":"wiping","шүүрдэх":"sweeping","тоос сорох":"vacuuming",
"засах":"repairing","бүтээх":"creating","хийж бүтээх":"crafting","угсрах":"assembling","задлан авах":"dismantling",
"барих (барилга)":"building","босгох":"erecting","нураах":"demolishing","малтах":"digging","булах":"burying",
"тарих":"planting","хураах":"harvesting","саах":"milking","хяргах":"shearing","эсгэх":"cutting out cloth",
"оёх":"sewing","нэхэх":"weaving","сүлжих":"braiding","зангидах":"knotting","хатгах (хатгамал)":"embroidering",
"будах (өнгөөр)":"painting","зурах":"drawing","сийлэх":"carving","цутгах (металл)":"casting","давтах (төмөр)":"forging",
"асаах":"lighting","унтраах":"extinguishing","шатаах":"burning","чанах":"boiling","шарах":"roasting",
"хайрах":"frying","хатаах":"drying","хөлдөөх":"freezing","халаах":"heating","хөргөх":"cooling",
"идэх":"eating","уух":"drinking","залгих":"swallowing","зажлах":"chewing","амтлах":"tasting","үнэрлэх":"sniffing",
"тэвэрэх":"embracing","үнсэх":"kissing","илбэх (толгойг)":"patting","цохих":"striking","алгадах":"slapping",
"өшиглөх":"kicking","түлхэн унагах":"shoving over","хамгаалах":"protecting","халхлах":"shielding"
}});

WB.dict.add({ id:"verb-mind", label:"Үйл үг · сэтгэхүй, мэдрэхүй, яриа", icon:"🗣", w:{
"харах":"looking","ширтэх":"staring","ажиглах":"observing","анзаарах":"noticing","үзэх":"watching",
"хараад өнгөрөх":"glancing","нүд салгахгүй харах":"gazing fixedly","эргэн тойрноо харах":"looking around",
"сонсох":"listening","чагнах":"listening intently","дуулах (сонсох)":"hearing","үнэрлэх (мэдрэх)":"smelling",
"амтлан үзэх":"savouring","мэдрэх":"sensing","таних":"recognising","ялгах":"distinguishing","анзаарахгүй":"overlooking",
"бодох":"thinking","эргэцүүлэх":"pondering","тунгаах":"contemplating","төсөөлөх":"imagining","зохиох":"inventing",
"санах":"remembering","дурсах":"reminiscing","мартах":"forgetting","мэдэх":"knowing","ойлгох":"understanding",
"таах":"guessing","мэдрэн ойлгох":"intuiting","сурах":"learning","судлах":"studying","заах":"teaching",
"тайлбарлах":"explaining","ухаарах":"realising","эргэлзэх":"doubting","итгэх":"believing","найдах":"hoping",
"хүсэх":"wishing","хүсэн мөрөөдөх":"dreaming of","шийдэх":"deciding","төлөвлөх":"planning","сонгох":"choosing",
"жиших":"comparing","дүгнэх":"judging","шүүмжлэх":"criticising","магтах":"praising","зөвшөөрөх":"approving",
"татгалзах":"refusing","эсэргүүцэх":"objecting","зөвшилцөх":"agreeing","маргах":"arguing","ятгах":"persuading",
"тохиролцох":"coming to terms","амлах":"promising","тангараглах":"swearing","уучлах":"forgiving",
"ярих":"speaking","хэлэх":"saying","өгүүлэх":"recounting","дуулгах":"informing","мэдэгдэх":"announcing",
"асуух":"asking","хариулах":"answering","дуудах":"calling","хашгирах":"shouting","орилох":"screaming",
"шивнэх":"whispering","бувтнах":"muttering","гундах":"grumbling","гуйх":"pleading","залбирах":"praying",
"дуулах":"singing","аялах (дуу)":"humming","хөөмийлөх":"throat singing","хөгжимдөх":"playing music",
"инээх":"laughing","мушийх":"smirking","инээмсэглэх":"smiling","уйлах":"weeping","уйлан гүйх":"sobbing",
"санаа алдах":"sighing","амьсгаадах":"panting","амьсгалах":"breathing","хамар шуухиртах":"sniffling",
"унтах":"sleeping","нойрсох":"slumbering","зүүдлэх":"dreaming","сэрэх":"waking","сэрээх":"awakening someone",
"анивчих":"blinking","нүдээ аних":"closing the eyes","эмээх":"dreading","айх":"fearing","гайхах":"marvelling",
"баярлах":"rejoicing","гуних":"grieving","уурлах":"getting angry","тайвшрах":"calming down","тэвчих":"enduring",
"хайрлах":"loving","үзэн ядах":"hating","өрөвдөх":"pitying","атаархах":"envying","бахархах":"taking pride"
}});
