/* ═══ 29 · Промт хэллэг II — орчин, гэрэл, агшин ═══ */
WB.dict.add({ id:"promt-env", label:"Промт хэллэг · орчин, цаг", icon:"🏞", w:{
"өргөн уудам хээр талд":"across a vast open steppe","эцэс төгсгөлгүй тал дунд":"in the middle of an endless plain",
"уулын бэлд":"at the foot of a mountain","уулын оройн дээр":"atop a mountain peak","хавцлын гүнд":"deep in a gorge",
"хөндийн дундуур":"through the middle of a valley","голын эрэг дээр":"on a riverbank","нуурын хажууд":"beside a lake",
"далайн эрэг дээр":"on the sea shore","элсэн манхан дунд":"among the sand dunes","говийн зэлүүд газарт":"in the empty Gobi",
"ойн гүнд":"deep in the forest","ойн захад (промт)":"at the edge of the woods","цасан талбай дээр":"on a snowfield",
"мөсөн голын дээгүүр":"over a glacier","хадан хясааны дэргэд":"beside a rocky outcrop","агуйн аманд":"at the mouth of a cave",
"эртний балгасын дунд":"among ancient ruins","овооны дэргэд":"beside an ovoo cairn","гэрийн үүдэнд":"at the door of a ger",
"гэрийн дотор галын дэргэд":"inside a ger beside the fire","хотын гудамжинд":"on a city street",
"хоосон гудамжаар":"along an empty street","хүн дүүрэн зах дээр":"in a crowded market","нарийн гудамжны булан":"a corner of a narrow alley",
"дээвэр дээр":"on a rooftop","цонхны дэргэд":"by a window","хаалганы босгон дээр":"on a threshold",
"шатны дээд талд":"at the top of the stairs","коридорын төгсгөлд":"at the end of a corridor",
"хоосон танхимд":"in an empty hall","сүмийн дотор":"inside a temple","замын дундуур":"in the middle of a road",
"галт тэрэгний вагонд":"in a railway carriage","машины доторх":"inside a car","аяны замд":"on the road of a journey",
"нар мандахын өмнөх агшин":"the moment before sunrise","нар жаргахын дараа":"just after sunset",
"үүр цайхын өмнөх харанхуй":"the darkness before dawn","шөнийн гүн":"the depth of night",
"үдийн халуунд":"in the midday heat","үдшийн сэрүүнд":"in the cool of the evening",
"хаврын анхны өдөр":"on the first day of spring","зуны халуун үдэш":"a hot summer evening",
"намрын сэрүүн өглөө":"a cool autumn morning","өвлийн харанхуй үүр":"a dark winter dawn",
"бороо орсны дараа":"after the rain has passed","цас орсны дараа":"after the snow has fallen",
"шуурганы дараа":"in the wake of the storm","манан татсан үед":"as the fog lifts",
"үүл нар халхлах үед":"as clouds pass over the sun","сүүдэр урт болох цагт":"at the hour of long shadows"
}});

WB.dict.add({ id:"promt-mood", label:"Промт хэллэг · уур амьсгал, агшин", icon:"🎭", w:{
"нам гүм байдал ноёрхоно":"a deep stillness prevails","чимээгүй байдал үргэлжилнэ":"the silence holds",
"цаг зогссон мэт санагдана":"time seems to stand still","агаар хүнд болно":"the air grows heavy",
"хурцадмал байдал өснө":"tension builds","юм болох гэж байгаа мэт":"as if something is about to happen",
"аюул ойртож байна":"danger is closing in","найдвар гэрэлтэнэ":"a glimmer of hope appears",
"бүх зүйл тайван":"everything is at peace","гэнэтийн өөрчлөлт":"an abrupt change",
"ганцаардлын мэдрэмж":"a sense of solitude","аглаг байдал":"a feeling of remoteness",
"эртний нууцлаг байдал":"an air of ancient mystery","сүр жавхлан":"an air of grandeur",
"эмзэглэлийн агшин":"a moment of tenderness","салах ёсны агшин":"a moment of parting",
"дахин уулзалтын агшин":"a moment of reunion","эргэлзээний агшин":"a moment of hesitation",
"шийдвэрийн агшин":"the moment of decision","илчлэлийн агшин":"the moment of revelation",
"эргэлтийн агшин":"the turning point","эцсийн агшин":"the final moment","эхлэлийн агшин":"the opening moment",
"дурсамжийн зөөлөн гэрэл":"the soft light of memory","гунигийн өнгө":"a shade of sorrow",
"баяр хөөрийн агшин":"a burst of joy","айдсын хүйтэн мэдрэмж":"a cold thread of fear",
"эв нэгдлийн мэдрэмж":"a sense of belonging","хагацлын гуниг":"the ache of separation",
"хүлээлтийн чимээгүй":"the quiet of waiting","эцсийн амьсгалын чимээгүй":"the hush of a last breath",
"хүн хоорондын зай":"the distance between people","үг хэлээгүй хайр":"unspoken love",
"хэлээгүй үлдсэн үг":"words left unsaid","мартагдсан амлалт":"a forgotten promise",
"хугарсан итгэл":"broken trust","сэргэсэн итгэл":"trust restored","дуусаагүй яриа":"an unfinished conversation",
"эргэж ирэхгүй өнгөрсөн":"a past that will not return","дахин эхлэх боломж":"a chance to begin again",
"хувь заяаны эргэлт":"a turn of fate","тохиолдлын уулзалт":"a chance encounter",
"хүлээгдээгүй зочин":"an unexpected visitor","эзгүй байшингийн чимээ":"a sound in an empty house",
"хэн нэгний оршихуй":"the presence of someone","алсын дуу":"a distant voice","цуурай хариулна":"an echo answers"
}});

WB.dict.add({ id:"promt-action", label:"Промт хэллэг · үйлдэл, хөдөлгөөн", icon:"🎯", w:{
"аажим эргэн харна":"slowly turns to look","гэнэт эргэнэ":"turns sharply","алсыг чиглэн алхана":"walks toward the horizon",
"нүүрээ салхи руу тавина":"turns a face into the wind","толгойгоо өргөнө":"lifts the head",
"толгойгоо гудайлгана":"bows the head","гараа сунган хүрнэ":"reaches out and touches",
"гараа буулгана":"lets the hand fall","хоёр гараа дэлгэнэ":"spreads both arms","нударгаа чанга атгана":"clenches a fist tight",
"хутгаа сугална":"draws a knife","сэлмээ хуйнаас сугална":"draws a sword from its scabbard",
"нумаа татна":"draws a bow","сум харвана":"looses an arrow","морио жолоодон эргүүлнэ":"reins the horse around",
"мориноосоо буун ирнэ":"dismounts","эмээл дээрээ бөхийнө":"leans low in the saddle",
"газар өвдөглөн суулаа":"kneels to the ground","чулуун дээр суулаа":"sits down on a stone",
"галд түлээ нэмнэ":"feeds wood to the fire","гараа галд ээнэ":"warms the hands at the fire",
"аягаа хоёр гараар өргөнө":"raises the bowl with both hands","хадаг дэлгэн барина":"holds out a khadag",
"хаалга нээж орно":"pushes open a door and enters","хаалгыг чимээгүй хаана":"closes the door without a sound",
"цонхоор гадагш ширтэнэ":"stares out of the window","хөшигийг татна":"draws back a curtain",
"дэнлүүгээ өргөнө":"lifts a lantern","гэрлээ унтраана":"puts out the light","лаа асаана":"lights a candle",
"захидлыг дэлгэнэ":"unfolds a letter","номоо хаана":"closes a book","зургийг эргүүлж харна":"turns a photograph over",
"зүүлтээ атгана":"clutches a pendant","бөгжөө тайлна":"slips off a ring","цүнхээ мөрөндөө үүрнэ":"slings a bag over the shoulder",
"нөмрөгөө нөмөрнө":"pulls a cloak around","малгайгаа тайлна":"takes off a hat","үсээ засна":"smooths the hair",
"нулимсаа арчина":"wipes away a tear","инээмсэглэн харна":"looks up with a smile",
"нүдээ анин амьсгаа авна":"closes the eyes and breathes in","гүн амьсгаа гарган зогсоно":"stands and lets out a long breath",
"алхаагаа зогсооно":"halts mid-step","хойшоо ухарна":"backs away","урагш нэг алхана":"takes a step forward",
"хажуу тийш харна":"glances to the side","эргэж хойшоо харна":"looks back over the shoulder","чимээгүйхэн явна":"leaves without a sound"
}});
