/* ═══ 37 · Промт хэллэг III — хэв маяг, зохиомж, өнгө ═══ */
WB.dict.add({ id:"promt-style", label:"Промт хэллэг · хэв маяг", icon:"🎨", w:{
"кино маягийн":"cinematic in style","баримтат маягийн дүрслэл":"documentary in style","гар зурсан маягийн":"hand-drawn in style",
"аниме маягийн":"in anime style","манга маягийн":"in manga style","хүүхэлдэйн кино маягийн":"in animated-film style",
"тосон зургийн маягийн":"in oil-painting style","усан будгийн маягийн":"in watercolour style",
"бэхэн зургийн маягийн":"in ink-wash style","модон барын маягийн":"in woodblock-print style",
"гэрэл зургийн маягийн":"photographic in style","хуучин зургийн маягийн":"in the style of an old photograph",
"хар цагаан кино маягийн":"in black-and-white film style","өнгө бүдгэрсэн кино маягийн":"in faded film stock style",
"ретро маягийн":"retro in style","ирээдүйн маягийн":"futuristic in style","эртний маягийн":"archaic in style",
"уламжлалт монгол маягийн":"in traditional Mongolian style","хээ угалзан чимэглэлтэй":"with ornamental scrollwork",
"тансаг чимэглэлтэй":"richly ornamented","энгийн цэвэрхэн загвартай":"clean and minimal in design",
"нарийн деталтай":"highly detailed","нэн нарийвчилсан":"ultra-detailed","ерөнхий тоймтой":"loosely rendered",
"өндөр нарийвчлалтай":"high resolution","бодит дүрслэлтэй":"photorealistic","хэт бодит":"hyperrealistic",
"уран сэтгэмжит дүрслэл":"surreal imagery","мөрөөдлийн дүрслэл":"dreamlike imagery","домгийн дүрслэл":"mythic imagery",
"баатарлаг дүрслэл":"heroic imagery","намуун дүрслэл":"serene imagery","хатуу ширүүн дүрслэл":"gritty imagery",
"өнгө нь тансаг":"lush in colour","өнгө нь хязгаарлагдмал":"restrained in colour","монохром":"monochrome",
"дулаан өнгөний давамгайлал":"dominated by warm tones","хүйтэн өнгөний давамгайлал":"dominated by cool tones",
"алтан бор өнгөний аяс":"a golden-brown palette","хөх саарал өнгөний аяс":"a blue-grey palette",
"улаан хар өнгөний аяс":"a red-and-black palette","цайвар зөөлөн өнгө":"pale muted colours",
"хурц тод өнгө":"bright saturated colours","байгалийн өнгө":"natural colour","хиймэл өнгө":"synthetic colour",
"өндөр динамик хүрээ":"high dynamic range","зөөлөн шилжилттэй":"with smooth gradations","эрс шилжилттэй":"with abrupt transitions",
"кино тоосонцортой (стиль)":"with visible film grain","цэвэр дижитал":"clean digital finish",
"анаморф линзийн гажилттай":"with anamorphic distortion","өргөн өнцгийн гажилттай":"with wide-angle distortion",
"төвлөрсөн тэгш хэмтэй":"centred and symmetrical","чөлөөт зохиомжтой":"loosely composed"
}});

WB.dict.add({ id:"promt-neg", label:"Промт хэллэг · хориглох, нарийвчлал", icon:"🚫", w:{
"бүдгэрсэн байх ёсгүй":"must not be blurry","гажсан гар":"deformed hands","илүү хуруу":"extra fingers",
"илүү мөч":"extra limbs","гажсан царай":"distorted face","хоёр толгой":"two heads","давхардсан дүр":"duplicated figures",
"тэгш бус нүд":"mismatched eyes","хиймэл харагдац":"a plastic look","хэт өнгө ханасан":"oversaturated colour",
"хэт бараан дүрслэл":"an overly dark image","хэт цайвар дүрслэл":"a washed-out image","бага нарийвчлалтай":"low resolution",
"усан тэмдэг":"a watermark","гарын үсэг (зураг дээр)":"a signature on the image","текст гажилт":"garbled text",
"логотип":"a logo","хүрээний хиймэл ирмэг":"an artificial border","дуусаагүй дүрслэл":"an unfinished rendering",
"орчин үеийн хувцас (хориглох)":"modern clothing where it does not belong","машин (хориглох)":"vehicles where they do not belong",
"цахилгаан шон":"power poles","хиймэл барилга":"anachronistic buildings","хуванцар эд зүйл":"plastic objects",
"буруу цаг үеийн эд":"anachronistic props","илүү хүн":"extra people in frame","анхаарал сарниулах зүйл":"distracting elements",
"эмх замбараагүй дэвсгэр":"a cluttered background","хэт өтгөн сүүдэр":"crushed shadows","гэрэл хэт шатсан":"blown-out highlights",
"нүүр таних боломжгүй":"an unrecognisable face","биеийн харьцаа буруу":"incorrect body proportions",
"гарын байрлал буруу":"wrong hand placement","гэрлийн чиглэл зөрчилтэй":"inconsistent lighting direction",
"сүүдэр буруу унасан":"shadows falling the wrong way","хэтийн харагдац алдаатай":"faulty perspective",
"хэмжээ зөрчилтэй":"inconsistent scale","өнгө зөрчилтэй":"clashing colours","хувцас зөрчилтэй":"inconsistent costume",
"дүрийн харагдац өөрчлөгдсөн":"the character's appearance drifting","орчин зөрчилтэй":"an inconsistent setting",
"нэг дүр давтагдсан":"the same character repeated","камерын хөдөлгөөн хэт их":"excessive camera movement",
"хэт хурдан огтлолт":"cuts that are too fast","хөдөлгөөн тасалдсан":"broken motion","дүрс чичирсэн":"a shaky image",
"толгойн орой тасарсан":"the top of the head cropped","мөч тасарсан":"limbs cropped at the frame edge",
"нүүр хэсэгчлэн харагдсан":"a partially hidden face","дэвсгэр хэт тод":"an over-sharp background",
"дүр дэвсгэртэй нийлсэн":"the subject merging into the background","гэрэлтүүлэг хавтгай":"flat lighting"
}});

WB.dict.add({ id:"promt-cam2", label:"Промт хэллэг · дараалал, шилжилт", icon:"🎛", w:{
"эхний кадр":"the opening shot","хоёр дахь кадр":"the second shot","эцсийн кадр":"the closing shot",
"дараагийн кадарт":"in the next shot","өмнөх кадраас":"from the previous shot","кадраас кадарт":"from shot to shot",
"нэг кадраас нөгөө рүү шилжих":"cutting from one shot to the next","гэнэтийн шилжилт":"a hard cut",
"зөөлөн шилжилт":"a soft transition","гэрлээр шилжих":"a transition through light","харанхуйгаар шилжих":"a transition through darkness",
"хөдөлгөөнөөр шилжих":"a match cut on movement","дүрсээр шилжих":"a match cut on shape",
"чимээгээр шилжих":"a sound bridge","камер дүрийг дагана":"the camera follows the figure",
"камер дүрийг орхино":"the camera leaves the figure","камер зогсоод дүр гарна":"the camera holds as the figure exits",
"дүр камер руу алхана":"the figure walks toward the camera","дүр камераас холдоно":"the figure walks away from the camera",
"камер дүрийн урдуур өнгөрнө":"the camera passes in front of the figure","камер объектыг илрүүлнэ":"the camera reveals an object",
"камер аажим өргөгдөж бүх орчныг харуулна":"the camera rises to reveal the whole setting",
"камер доошилж нарийн деталь харуулна":"the camera lowers to a small detail","фокус урд талаас хойш шилжинэ":"focus shifts from foreground to background",
"фокус хойноос урагш шилжинэ":"focus shifts from background to foreground","дэвсгэр тодорно":"the background comes into focus",
"дүр бүдгэрнэ":"the subject falls out of focus","гэрэл аажим нэмэгдэнэ":"the light gradually rises",
"гэрэл аажим буурна":"the light gradually falls","өнгө аажим хувирна":"the colour slowly shifts",
"хөдөлгөөн удаашрана":"the motion slows","хөдөлгөөн хурдасна":"the motion accelerates","бүх зүйл хөлдөнө":"everything freezes",
"хөдөлгөөн дахин эхэлнэ":"the movement resumes","дуу чимээ алга болно":"the sound drops away",
"зөвхөн амьсгал сонсогдоно":"only breathing is heard","хөгжим орж ирнэ":"the music enters",
"кадрын урт гурван секунд":"a three-second shot","кадрын урт таван секунд":"a five-second shot",
"кадрын урт арван секунд":"a ten-second shot","нэг минутын кадр":"a one-minute take"
}});
